name: Trigger on new posts

on:
  push:
    paths:
      - '_posts/**'
jobs:
  new_post_detected:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Pip install
      run: pip install openai
 
    - name: Run main.py
      run: python main.py

    - name: Check for new posts
      run: |
        git diff --name-status HEAD~1 HEAD

        if git diff --name-status HEAD~1 HEAD | grep "^A" | grep "_posts/"; then
          echo "New files added in _posts, triggering workflow..."
        else
          echo "No new posts. Exiting."
          exit 0
        fi
